services:
  zapusk-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: zapusk-frontend
    container_name: zapusk-frontend-compose
    volumes:
      - ./html/:/tmp:rw
    ports:
      - "8080:80"
    restart: always